### ISSUE TITLE
Virtual Environment can not find package

### ISSUE THREAD

**Issue by richard-everette** [richardschoen/QshOni#21]
I have a virtual environment that has a package installed which is not installed in the main environment.  When I use the "use virtual environment" flag in the QSHPYRUN command, my python script does not find the package.  I duplicated the issue in the SSH Terminal and found that when python is hard coded to the OpenSys, the package could not be found.  When i just used the python by itself, the package was found.  I believe in the second case, it was using the python link located in the bin directory of the virtual environment.  My suggestion, and what I did on my installation, is to modify QSHPYRUNC.CLLE to leave PYPATH out of the PYEXE variable when using a virtual environment.

**Comment by richardschoen** [comment]
I have updated the QSHPYRUNC.CLLE member to support non-qualified paths. 

Install and compile this CL in QSHONI and then either set the PYPATH data area value to ' ' or pass ' ' for the PYPATH parameter value when calling QSHPYPATH. Setting the PYPATH data area value to blanks is probably the better fix because it will then use search path to locate your python binary.
