### ISSUE TITLE
Add argument to QSHPYRUN to set cwd to script directory

### ISSUE THREAD

**Issue by dkornacki-cutco** [richardschoen/QshOni#22]
I quickly glanced at issues and did a source search for CHGCURDIR, so I'm assuming this is currently possible directly with QSHPYRUN. Normally when I run a python script, I'll cd into the script directory then run the script from there. Currently when using QSHPYRUN, I just run a CHGCURDIR right before running it. This allows a `path.append('..')` to find a common utility package. The IBM defaults the cwd to user home directory I believe. But to make running SBMJOB commands with QSHPYRUN simpler, I think another boolean argument would be beneficial, where *YES would set cwd to script directory, i.e., just by running CHGCURDIR on the script directory. *NO would just keep current behavior.

**Comment by richardschoen** [comment]
Interesting. I have a couple of thoughts:  

If I were to add the parm to the QSHPYRUN command I would have a parm to probably just automatically append ```cd /scriptdir;``` to the python command so it looks like this:  ```cd /scriptdir;python3 scripname.py "parm1" Parm2"```  when it makes the actual command call via QSHEXEC from within QSHPYRUN.     

I probably would stay away from the CHGCURDIR command because it affects the main calling job as well as the QSH/PASE call.  I would rather only have it affect the called QSH/PASE command.

The CHGSCRDIR Parm would probably look something like thing:
```Change to script directory *NO/*YES``` with a default to *NO.

Another option you can do right now would be to use the QSHEXEC command to do the same thing yourself. today. Personally I tend to use QSHEXEC more often than the convenience wrappers.

Open to other thoughts.

**Comment by dkornacki-cutco** [comment]
Thanks for the workaround by directly using QSHEXEC. That will work great.

Yes, I think prefixing the cd command just before the python call will work perfectly. For some reason I thought there might've been a place to hook into the PASE/child job when first created to run the CHGCURDIR (rather than in the parent job), but I just saw the PASE job is opened by the QSH command. So there is no such hook, at least not that I'm aware of.

**Comment by dkornacki-cutco** [comment]
Well I guess there is a way to hook CL commands at the start of these jobs, just doing so in the same manner as you explained (i.e., command1;commands2;etc). For CL commands, they'd get called using the `cl` bash builtin. In this case, there is no point in using CHGCURDIR though because the cd command is available.

**Comment by richardschoen** [comment]
If you download and build: QSHPYRUN.CMD and QSHPYRUN.CLLE or rename QSHONI library and re-install you will get the QSHPYRUN updates. 

There is now a CHGSCRDIR option. Default-*NO.  
*YES removes path from script internally and does a cd into the directory where script is located before running.

**Comment by dkornacki-cutco** [comment]
Wow that was quick! I'll rebuild and test this out shortly. Thanks again.
